services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage

  llm:
    build:
      context: docker/llm
    ports:
      - "11434:11434"

  ingestor:
    image: ghcr.io/milairhu/compliance-corpus-ingestor:latest
#    build:
#      context: ~/Documents/Projets/compliance-corpus-ingester
    ports:
      - "8000:8000"
    depends_on:
      qdrant:
        condition: service_started
        restart: true
    volumes:
        - ./corpus:/app/corpus
    environment:
        - QDRANT_URL=http://qdrant:6333
        - CORPUS=/app/corpus

  compliance-auto-filler:
    build:
      context: .
    depends_on:
      ingestor:
        condition: service_started
        restart: true
    volumes:
      - ./:/app
    environment:
      - SOURCE_FILE=/app/questions.txt
      - OUTPUT_FILE=/app/answers.csv
      - QDRANT_URL=qdrant:6334
      - LLM_URL=http://llm:11434/api/generate
      - EMBEDDING_API_URL=http://ingestor:8000/embed
