services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage
  llm:
    image: ghcr.io/milairhu/compliance-form-filler-llm:latest
    ports:
      - "11434:11434"

  ingestor:
    image: ghcr.io/milairhu/compliance-corpus-ingestor:v0.0.4
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    volumes:
        - ./corpus:/app/corpus
    environment:
        - QDRANT_URL=http://qdrant:6333
        - CORPUS=/app/corpus

  compliance-auto-filler:
    build:
      context: .
    depends_on:
      - qdrant
      - llm
      - ingestor
    volumes:
      - ./questions.txt:/tmp/questions.txt
      - ./answers.csv:/tmp/answers.csv
    environment:
      - SOURCE_FILE=/tmp/questions.txt
      - OUTPUT_FILE=/tmp/answers.csv
      - QDRANT_URL=qdrant:6333
      - LLM_URL=http://llm:11434/api/generate
      - EMBEDDING_API_URL=http://ingestor:8000/embed
